### ISSUE TITLE
incompatible with new Webstorm 2023.2.2

### ISSUE THREAD

**Issue by viktorkovarik-devcors** [Alaanor/candid-intellij-plugin#106]
Hi can you rebuild candid plugin for new version of Jetbrain tools?

Thanks in advance!

**Comment by Alaanor** [comment]
Hello, thanks for telling me it :ok_hand: , I will try to spend some time tonight to check that.

It might not be a just a bump this time as rustrover got released and so I have to switch to the new rust plugin as deps.

**Comment by Alaanor** [comment]
There we go, [v0.3.5](https://github.com/Alaanor/candid-intellij-plugin/releases/tag/v0.3.5) is now available. The plugin is uploaded and waiting for Jetbrains' review and approval.

Next version bump (2023.2.3) gonna be difficult :cry: it break a lot of thing.

I'm closing the issue but don't hesitate to reopen if you got something to add.
