### ISSUE TITLE
incompatible with new Webstorm 2022.3

### ISSUE THREAD

**Issue by peterpeterparker** [Alaanor/candid-intellij-plugin#54]
Hi @Alaanor 👋

Just wanted to let you know that after upgrading Webstorm 2022.3 today, the editor indicated me that your plugin wasn't compatible with last version.

<img width="380" alt="Capture d’écran 2022-11-29 à 11 27 39" src="https://user-images.githubusercontent.com/16886711/204505621-e34351d0-2c5a-4053-816c-12f34654d1db.png">

**Comment by Alaanor** [comment]
@peterpeterparker Thanks for telling me, I will make an update this afternoon after my work hours. :+1:

**Comment by Alaanor** [comment]
There we go, [v0.3.3](https://github.com/Alaanor/candid-intellij-plugin/releases/tag/v0.3.3). If you don't want to wait on Jetbrain's manual verification of the update before it reach their marketplace, you can download the artifact on the release page on github and install it manually.

Closing the issue, if this by any chance this didn't solve your issue, feel free to reopen :)

**Comment by peterpeterparker** [comment]
Cool! No rush from my side, thanks for the upgrade 👍
